apiVersion: v1
kind: Service
metadata:
  name: e-commerce-service
spec:
  selector:
    app: e-commerce
  ports:
  - port: 80
    targetPort: 8000  # Le port de runserver dans le conteneur
  type: ClusterIP  # On utilise ClusterIP + port-forward (plus simple dans Codespaces)