# Generated by Django 6.0.2 on 2026-04-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_alter_commande_totalcde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('Alimentaire', 'Alimentaire'), ('Meuble', 'Meuble'), ('Sanitaire', 'Sanitaire'), ('Vaisselle', 'Vaisselle'), ('Vetement', 'Vêtement'), ('Jouets', 'Jouets'), ('Linge', 'Linge de Maison'), ('Bijoux', 'Bijoux'), ('Decor', 'Décor')], default='Alimentaire', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('em', 'emballé'), ('fr', 'Frais'), ('cs', 'Conserve')], default='em', max_length=2),
        ),
    ]
